working_base

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -17,15 +17,21 @@ services:
 
   nats:
     image: nats:2.10-alpine
-    command: ["-js"] # JetStream on (optional, but useful)
+    command: ["-js", "-m", "8222"] # JetStream on (optional)
     ports:
       - "4222:4222"
       - "8222:8222" # monitoring
     healthcheck:
-      test: ["CMD-SHELL", "wget -qO- http://localhost:8222/healthz >/dev/null 2>&1 || exit 1"]
-      interval: 5s
+      test: ["CMD", "sh", "-c", "nc -z localhost 4222 || exit 1"]
+      interval: 10s
       timeout: 5s
-      retries: 30
+      retries: 3
+      
+    # healthcheck:
+    #   test: ["CMD-SHELL", "wget -qO- http://localhost:8222/healthz >/dev/null 2>&1 || exit 1"]
+    #   interval: 5s
+    #   timeout: 5s
+    #   retries: 30
 
   minio:
     image: minio/minio:RELEASE.2025-01-20T14-49-07Z
@@ -38,22 +44,24 @@ services:
       - "9001:9001" # Console UI
     volumes:
       - miniodata:/data
-    healthcheck:
-      test: ["CMD-SHELL", "wget -qO- http://localhost:9000/minio/health/ready >/dev/null 2>&1 || exit 1"]
-      interval: 5s
-      timeout: 5s
-      retries: 30
+    # ВАЖНО: healthcheck убран намеренно.
+    # В образе minio нет curl/wget, из-за чего healthcheck "ломается" и контейнер становится unhealthy,
+    # хотя сервис реально работает 100/100
 
-  # One-shot init: create bucket & set it public/private if needed
+  # One-shot init: wait for MinIO, then create bucket
   minio-init:
     image: minio/mc:RELEASE.2025-01-17T23-25-50Z
     depends_on:
-      minio:
-        condition: service_healthy
+      - minio
     entrypoint: ["/bin/sh", "-lc"]
     command: >
-      mc alias set local http://minio:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY} &&
-      mc mb -p local/${S3_BUCKET} || true &&
+      i=0;
+      until mc alias set local http://minio:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY}; do
+        i=$$((i+1));
+        echo "waiting for minio... attempt=$$i";
+        sleep 1;
+      done;
+      mc mb -p local/${S3_BUCKET} || true;
       mc anonymous set none local/${S3_BUCKET} || true
     restart: "no"
 
@@ -66,19 +74,18 @@ services:
     working_dir: /workspace
     volumes:
       - ./:/workspace:cached
-    user: "${UID}:${GID}"
+    # user: "${UID}:${GID}" dev container конфликт, vscode usr vs orig user
     depends_on:
       db:
         condition: service_healthy
       nats:
         condition: service_healthy
-      minio:
-        condition: service_healthy
       minio-init:
         condition: service_completed_successfully
     ports:
       - "8080:8080"
-    command: ["sh", "-lc", "go test ./... && go run ./cmd/api"]
+    command: ["sleep", "infinity"] # dev
+    # command: ["sh", "-lc", "go test ./... && go run ./cmd/api"] # prod
 
 volumes:
   pgdata:
